server:
  port: 25000
spring:
  application:
    name: umi-gateway
logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          alibaba:
            sentinel: debug
            nacos: debug
          gateway: debug
umisoft:
  gateway:

